name: "Bookshelf Action: Issue Comment"
on:
  issue_comment:
    types: [created]
jobs:
  bookshelf-action:
    name: Bookshelf Action
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Bookshelf Action
        uses: AnandChowdhary/bookshelf-action@HEAD
        with:
          command: "onIssueComment"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
